/* DO NOT EDIT THIS FILE - it is machine generated by ftc-rust v11.1.1.
 * DO NOT touch this comment! It is used to identify classes as machine generated for various purposes.
 * DO NOT touch the code overall either! It will be overwritten if you do, and if you don't remove this comment after changing it this file will probably be removed by a build script.
 */

package org.firstinspires.ftc.teamcode;

import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;

@TeleOp(name = "Example: My Iterative Op Mode", group = "Example")

public class MyIterativeOpMode extends OpMode {
    private long rust_id;
    @Override
    public native void init();
    @Override
    public native void init_loop();
    @Override
    public native void start();
    @Override
    public native void loop();
    @Override
    public native void stop();

    static {
        System.loadLibrary("team_code_rust");
    }
}
