/* DO NOT EDIT THIS FILE - it is machine generated by the FTC rust proc macro */

package org.firstinspires.ftc.teamcode;

import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;

@TeleOp(name = "Example: My Linear Op Mode", group = "Example")

public class MyLinearOpMode extends LinearOpMode {
    @Override
    public native void runOpMode();

    static {
        System.loadLibrary("team_code_rust");
    }
}
