/* DO NOT EDIT THIS FILE - it is machine generated by ftc-rust v11.1.1.
 * DO NOT touch this comment! It is used to identify classes as machine generated for various purposes.
 * DO NOT touch the code overall either! It will be overwritten if you do, and if you don't remove this comment after changing it this file will probably be removed by a build script.
 */

package org.firstinspires.ftc.teamcode;

import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;

@TeleOp(name = "Example: My Linear Op Mode", group = "Example")

public class MyLinearOpMode extends LinearOpMode {
    private long rust_id;
    @Override
    public native void runOpMode();

    static {
        System.loadLibrary("team_code_rust");
    }
}
